- hosts: [terraform-ansible]
  tasks:
    - name: criar o aquivo 
      copy:
        dest: /home/ubuntu/index.html
        content: <h1> Feito com terraform e ansible </h1>
                 <h2> Esse "Bilete" eh verdade </h2>
    - name: criando o servidor
      shell: "nohup busybox httpd -f -p 8080 &"